import type { GuideData } from "@/components/guides/GuideArticle";
const relatedSalary = [{ href: "/guides/salary-work", label: "급여·노동 가이드 모음" }];
const relatedFinance = [{ href: "/guides/finance", label: "금융 가이드 모음" }];
const relatedProperty = [{ href: "/guides/property", label: "주택·부동산 가이드 모음" }];
export const guideData = {
  salary: { path: "/guides/salary-net-pay-guide", title: "연봉 실수령액이 달라지는 이유", intro: "같은 세전 연봉이라도 매월 받는 금액은 상여 지급 방식, 비과세 항목, 사회보험료, 부양가족과 원천징수 조건에 따라 달라집니다. 실수령액 숫자 하나보다 어떤 항목이 공제되는지 이해하는 것이 먼저입니다.", sections: [{ title: "세전 연봉과 월 실수령액", paragraphs: ["연봉을 12개월로 단순히 나눈 금액은 월 세전 급여일 뿐입니다. 국민연금, 건강보험, 장기요양보험, 고용보험과 소득세·지방소득세가 공제된 뒤 실제 지급액이 정해집니다."] }, { title: "비과세와 상여금의 영향", paragraphs: ["식대 등 비과세 항목은 요건과 한도가 있으며 회사의 급여 구성에 따라 다릅니다. 상여와 성과급이 특정 달에 지급되면 월별 실수령액도 고르게 나오지 않습니다."] }, { title: "연말정산과 다른 이유", paragraphs: ["매월 원천징수는 최종 세액 확정이 아닙니다. 연말정산에서 소득·세액공제를 반영하면 환급 또는 추가 납부가 생길 수 있으므로 계산 결과를 연말정산 예상치로 사용하면 안 됩니다."] }], calculatorHref: "/calculators/salary-net-pay", calculatorLabel: "연봉 실수령액 기준 확인하기", related: relatedSalary },
  weekly: { path: "/guides/weekly-holiday-pay-guide", title: "주휴수당, 계산 전에 확인할 조건", intro: "주휴수당은 실제 일한 시간만으로 결정되지 않습니다. 주 소정근로시간, 소정근로일 개근 여부와 근로형태를 함께 확인해야 합니다.", sections: [{ title: "주 15시간 기준", paragraphs: ["근로기준법상 4주 평균 1주 소정근로시간이 15시간 미만인 근로자에게는 주휴일 규정이 적용되지 않습니다. 일시적으로 더 일한 시간과 계약상 소정근로시간은 구분해야 합니다."] }, { title: "개근 조건", paragraphs: ["근로계약에서 정한 소정근로일을 모두 근무했는지 확인해야 합니다. 결근과 지각·조퇴, 사용자 귀책 휴업 등은 동일하게 단정할 수 없어 실제 사실관계 확인이 필요합니다."] }, { title: "단순 계산의 한계", paragraphs: ["불규칙 근무나 근로일별 시간이 다른 경우 산식이 복잡해질 수 있습니다. 연장·야간·휴일 가산수당과 최저임금 준수 여부도 이 계산기에는 포함하지 않습니다."] }], calculatorHref: "/calculators/weekly-holiday-pay", calculatorLabel: "주휴수당 계산하기", related: relatedSalary },
  savings: { path: "/guides/savings-interest-guide", title: "예금과 적금 이자, 어떻게 달라질까요?", intro: "예금은 목돈을 한 번에 맡기고, 적금은 일정 금액을 나누어 납입합니다. 같은 금리라도 실제로 이자가 붙는 원금과 기간이 달라 만기 이자는 같지 않습니다.", sections: [{ title: "예금과 적금의 차이", paragraphs: ["예금은 예치한 원금 전체가 처음부터 이자를 얻지만, 적금은 회차별 납입금마다 이자가 붙는 기간이 다릅니다. 따라서 연이율만 보고 두 상품의 이자를 직접 비교하면 오해할 수 있습니다."] }, { title: "단리와 복리", paragraphs: ["단리는 원금에만 이자가 붙고 복리는 발생한 이자가 다시 원금에 더해져 이자를 만듭니다. 실제 상품이 월복리인지, 일복리인지 또는 단리인지 약관을 확인해야 합니다."] }, { title: "세전과 세후", paragraphs: ["일반과세 예금 이자에는 이자소득세와 지방소득세가 원천징수됩니다. 비과세와 세금우대는 가입 자격과 상품 요건이 있으므로 임의로 적용할 수 없습니다."] }], calculatorHref: "/calculators/savings-interest", calculatorLabel: "예·적금 이자 계산하기", related: relatedFinance },
  brokerage: { path: "/guides/real-estate-brokerage-fee-guide", title: "부동산 중개보수 계산 전 확인할 점", intro: "중개보수는 거래금액에 요율을 곱한 확정 수수료가 아닙니다. 물건과 거래 유형, 중개사무소 소재지 관할 조례에 따른 상한 안에서 실제 보수를 협의합니다.", sections: [{ title: "상한요율과 협의", paragraphs: ["법과 시·도 조례는 받을 수 있는 한도를 정합니다. 실제 지급할 보수는 그 상한 이내에서 중개의뢰인과 개업공인중개사가 협의해 결정합니다."] }, { title: "월세 거래금액", paragraphs: ["월세는 보증금에 월차임의 100배를 더해 거래금액을 산정하고, 합계가 5천만 원 미만이면 월차임의 70배를 더하는 규칙을 적용합니다."] }, { title: "부가세와 지역 차이", paragraphs: ["중개보수의 부가가치세는 별도일 수 있습니다. 또한 중개대상물 소재지와 중개사무소 소재지가 다를 때 적용 조례를 주의해서 확인해야 합니다."] }], calculatorHref: "/calculators/real-estate-brokerage-fee", calculatorLabel: "서울·경기·인천 주택 중개보수 상한 계산하기", related: relatedProperty },
  rent: { path: "/guides/monthly-rent-conversion-guide", title: "보증금과 월세를 전환할 때 알아둘 점", intro: "보증금과 월세를 서로 바꿀 때 사용하는 전환율은 계약 조건과 법정 상한을 함께 확인해야 합니다. 단순 환산액만으로 실제 계약의 유불리를 판단하기는 어렵습니다.", sections: [{ title: "보증금 감소와 월세 증가", paragraphs: ["보증금을 줄이는 금액에 연 전환율을 곱하고 12로 나누면 월세 증가분의 단순 참고치를 구할 수 있습니다. 관리비와 다른 특약은 별도로 보아야 합니다."] }, { title: "월세를 보증금으로 환산", paragraphs: ["월세 감소액에 12를 곱한 뒤 연 전환율로 나누어 보증금 환산액을 구할 수 있습니다. 전환율이 0이면 역산할 수 없습니다."] }, { title: "법정 기준과 계약 조건", paragraphs: ["법정 전월세전환율은 모든 임대차 상황을 자동으로 확정하는 숫자가 아닙니다. 적용 시점과 계약 갱신 여부, 주택임대차보호법 적용 범위를 확인해야 합니다."] }], calculatorHref: "/calculators/monthly-rent-conversion", calculatorLabel: "사용자 입력 전환율로 계산하기", related: relatedProperty },
} satisfies Record<"salary" | "weekly" | "savings" | "brokerage" | "rent", GuideData>;
