import type { Phase2PageData } from "@/components/calculator/Phase2CalculatorPage";
import { LABOR_STANDARDS_REFERENCE } from "./laborStandards";
import { SAVINGS_INTEREST_REFERENCE } from "./savingsInterestRates";
import { BROKERAGE_REFERENCE } from "./brokerageFeeRates";
import { RENT_CONVERSION_REFERENCE } from "./rentConversionRates";
import { SALARY_REFERENCE } from "./salaryTaxRates";

const commonCautions = ["결과는 입력 조건에 따른 참고용 예상값이며 확정 금액이 아닙니다.", "제도와 기준은 변경될 수 있으므로 실제 의사결정 전에 공식 기관의 최신 안내를 확인하세요.", "지원 범위 밖 조건에는 임의 수치를 적용하지 않습니다.", "입력한 값은 브라우저에서만 계산되며 서버에 저장되지 않습니다."];
const faq = (subject: string, special: string) => [{ question: `${subject} 결과는 실제 금액과 같나요?`, answer: "아니요. 입력 조건을 단순화한 참고용 예상값이며 실제 계약·상품·고지 조건에 따라 달라질 수 있습니다." }, { question: "입력값이 저장되나요?", answer: "아니요. 계산은 브라우저에서 처리되며 입력값을 서버나 데이터베이스에 저장하지 않습니다." }, { question: "결과가 달라지는 주요 이유는 무엇인가요?", answer: special }, { question: "지원하지 않는 조건은 어떻게 처리하나요?", answer: "확인되지 않은 수치를 억지로 적용하지 않고 지원 범위 밖 또는 별도 확인 필요 상태를 표시합니다." }, { question: "실제 의사결정 전에 무엇을 확인해야 하나요?", answer: "페이지에 표시된 공식 출처와 기준일을 확인하고, 금융기관·관할기관 또는 전문가에게 실제 적용 조건을 문의하세요." }];

export const phase2PageData = {
  salary: { kind: "salary", path: "/calculators/salary-net-pay", title: "연봉 실수령액 계산기", description: "연봉과 월급의 공제 구조를 이해하고 실제 급여명세서에서 확인해야 할 항목을 안내합니다. 근로소득 간이세액표 검증 전에는 오해를 막기 위해 수치 결과를 제한합니다.", category: "급여·노동 계산기", categoryHref: "/salary-work", guideHref: "/guides/salary-net-pay-guide", guideTitle: "연봉 실수령액이 달라지는 이유", reference: SALARY_REFERENCE, useful: ["세전 연봉과 실수령액의 차이를 이해할 때", "급여명세서에서 공제 항목을 확인할 때", "입사 전 연봉 조건을 비교할 때"], steps: ["연봉 또는 월급 기준을 확인합니다.", "비과세 항목과 부양가족 조건을 확인합니다.", "4대보험 및 원천징수 고지액은 실제 급여명세서와 대조합니다."], example: "연봉 5,000만 원이라도 비과세 식대, 부양가족, 상여 지급 방식과 보험료 기준소득에 따라 월 실수령액이 달라질 수 있습니다.", cautions: commonCautions, faqs: faq("연봉 실수령액", "보험료 상·하한, 비과세 항목, 부양가족, 원천징수와 연말정산 차이 때문입니다."), related: [{ href: "/calculators/severance-pay", label: "퇴직금 계산기" }, { href: "/calculators/weekly-holiday-pay", label: "주휴수당 계산기" }] },
  weekly: { kind: "weekly", path: "/calculators/weekly-holiday-pay", title: "주휴수당 계산기", description: "시급, 주 소정근로시간, 소정근로일수와 개근 여부를 바탕으로 시간급 근로자의 주·월 예상 주휴수당을 단순 계산합니다.", category: "급여·노동 계산기", categoryHref: "/salary-work", guideHref: "/guides/weekly-holiday-pay-guide", guideTitle: "주휴수당, 계산 전에 확인할 조건", reference: LABOR_STANDARDS_REFERENCE, useful: ["아르바이트 급여를 확인할 때", "주 15시간 기준 충족 여부를 살펴볼 때", "근로계약서의 소정근로일과 시간을 확인할 때"], steps: ["시급을 입력합니다.", "주당 소정근로시간과 근무일수를 입력합니다.", "개근 여부를 선택하고 계산합니다."], example: "시급 10,000원, 주 20시간, 주 5일, 개근으로 입력하면 단순 주휴시간은 4시간이며 주 예상액은 40,000원입니다.", cautions: commonCautions, faqs: faq("주휴수당", "4주 평균 소정근로시간, 개근, 불규칙 근무 및 적용 예외에 따라 달라질 수 있습니다."), related: [{ href: "/calculators/salary-net-pay", label: "연봉 실수령액 계산기" }, { href: "/calculators/severance-pay", label: "퇴직금 계산기" }] },
  savings: { kind: "savings", path: "/calculators/savings-interest", title: "예·적금 이자 계산기", description: "예금과 적금의 고정 연이율, 기간, 단리·월복리 조건을 입력해 세전 이자와 일반과세 기준 세후 예상 수령액을 확인합니다.", category: "금융 계산기", categoryHref: "/finance", guideHref: "/guides/savings-interest-guide", guideTitle: "예금과 적금 이자, 어떻게 달라질까요?", reference: SAVINGS_INTEREST_REFERENCE, useful: ["예금과 적금의 예상 이자를 비교할 때", "단리와 월복리 차이를 확인할 때", "세전 이자와 일반과세 후 금액을 비교할 때"], steps: ["예금 또는 적금을 선택합니다.", "예치금이나 월 납입액, 금리와 기간을 입력합니다.", "이자 방식과 과세 유형을 선택합니다."], example: "1,000만 원을 연 3% 단리로 12개월 예치하면 세전 예상 이자는 30만 원이며 일반과세를 선택하면 15.4%를 단순 적용합니다.", cautions: commonCautions, faqs: faq("예·적금 이자", "납입일, 일수 계산, 우대금리, 중도해지 및 과세 특례에 따라 달라집니다."), related: [{ href: "/calculators/loan-interest", label: "대출 이자 계산기" }] },
  brokerage: { kind: "brokerage", path: "/calculators/real-estate-brokerage-fee", title: "부동산 중개보수 계산기", description: "서울 소재 주택의 매매·전세·월세 거래금액을 기준으로 한 중개보수 상한액을 참고용으로 계산합니다. 실제 보수는 상한 이내에서 협의합니다.", category: "세금·부동산 계산기", categoryHref: "/property-tax", guideHref: "/guides/real-estate-brokerage-fee-guide", guideTitle: "부동산 중개보수 계산 전 확인할 점", reference: BROKERAGE_REFERENCE, useful: ["서울에서 주택 매매 계약을 준비할 때", "전세·월세 중개보수 상한을 확인할 때", "부가세와 중개보수를 구분할 때"], steps: ["지역과 주택 여부를 선택합니다.", "거래 유형과 거래금액을 입력합니다.", "상한요율과 상한액을 확인하고 실제 보수는 중개사와 협의합니다."], example: "서울 소재 5억 원 주택 매매는 해당 구간 상한요율 0.4%를 적용한 200만 원이 예상 상한액이며 부가세는 별도일 수 있습니다.", cautions: commonCautions, faqs: faq("중개보수", "중개사무소 소재지의 시·도 조례, 거래 유형, 협의 요율과 부가세에 따라 달라집니다."), related: [{ href: "/calculators/home-acquisition-tax", label: "주택 취득세 계산기" }, { href: "/calculators/monthly-rent-conversion", label: "월세 전환 계산기" }] },
  rent: { kind: "rent", path: "/calculators/monthly-rent-conversion", title: "월세 전환 계산기", description: "보증금 일부를 월세로 바꾸거나 월세 일부를 보증금으로 환산할 때 사용자가 직접 입력한 전환율 기준의 단순 예상액을 확인합니다.", category: "세금·부동산 계산기", categoryHref: "/property-tax", guideHref: "/guides/monthly-rent-conversion-guide", guideTitle: "보증금과 월세를 전환할 때 알아둘 점", reference: RENT_CONVERSION_REFERENCE, useful: ["보증금을 낮추고 월세를 높이는 조건을 비교할 때", "월세 감소분을 보증금으로 환산할 때", "계약서의 전환율 의미를 이해할 때"], steps: ["계산 방향을 선택합니다.", "보증금 또는 월세 변동액을 입력합니다.", "계약에서 확인한 연 전환율과 기간을 입력합니다."], example: "보증금 1,000만 원 감소분을 사용자가 입력한 연 6%로 환산하면 월 예상 증가액은 5만 원입니다.", cautions: commonCautions, faqs: faq("월세 전환", "법정 상한, 계약 시점, 주택 유형, 특약과 실제 협의 조건에 따라 달라집니다."), related: [{ href: "/calculators/real-estate-brokerage-fee", label: "부동산 중개보수 계산기" }, { href: "/calculators/home-acquisition-tax", label: "주택 취득세 계산기" }] },
} satisfies Record<"salary" | "weekly" | "savings" | "brokerage" | "rent", Phase2PageData>;
