import type { PolicyData } from "@/components/policies/PolicyArticle";

const loanLinks = [{ label: "대출 이자 계산기", href: "/calculators/loan-interest" }, { label: "월세 전환 계산기", href: "/calculators/monthly-rent-conversion" }];
const salaryLinks = [{ label: "연봉 실수령액 계산기", href: "/calculators/salary-net-pay" }, { label: "퇴직금 계산기", href: "/calculators/severance-pay" }];

export const policyData = {
  youthJeonse: { category: "주거·부동산", title: "청년전용 버팀목전세자금: 신청 전 확인사항", summary: "청년전용 버팀목전세자금은 무주택 청년의 전세보증금 마련을 지원하는 주택도시기금 상품입니다. 금리만 비교하지 말고 나이, 세대주, 소득·자산, 대상주택과 보증 가능 여부를 순서대로 확인해야 합니다.", status: "공식 상품 운영 확인", checkedAt: "2026-09-02", audience: ["전세 계약을 앞둔 무주택 청년", "일반 은행 전세대출과 정책대출 이자를 비교하는 사람"], benefits: ["주택도시기금 기준에 따른 전세자금 대출을 심사합니다.", "실제 금리와 한도는 접수일의 상품 기준과 소득·자산 심사에 따라 결정됩니다."], checks: ["본인과 세대원의 무주택 요건을 확인하세요.", "임대차계약서, 계약금 지급과 신청시기 요건을 확인하세요.", "대출 승인과 반환보증 가입 가능 여부는 별도일 수 있습니다."], sourceName: "주택도시기금 청년전용 버팀목전세자금", sourceUrl: "https://nhuf.molit.go.kr/FP/FP05/FP0502/FP05020301.jsp", related: loanLinks },
  newlywedJeonse: { category: "주거·부동산", title: "신혼부부 전세자금대출: 버팀목 확인 순서", summary: "신혼부부전용 전세자금은 혼인기간, 무주택, 부부합산 소득·자산과 대상주택 조건을 함께 심사합니다.", status: "공식 상품 운영 확인", checkedAt: "2026-09-02", audience: ["전세 신혼집을 구하는 무주택 신혼부부", "혼인 예정자로 정책 전세자금을 비교하는 사람"], benefits: ["주택도시기금의 신혼부부 전용 조건으로 전세자금을 심사합니다.", "지역과 자녀 수 등에 따라 한도와 우대조건이 달라질 수 있습니다."], checks: ["혼인기간 또는 결혼예정 증빙 요건을 확인하세요.", "부부합산 소득과 순자산 기준을 확인하세요.", "대상주택과 보증기관 심사 가능 여부를 계약 전에 확인하세요."], sourceName: "주택도시기금 신혼부부전용 전세자금", sourceUrl: "https://nhuf.molit.go.kr/FP/FP05/FP0502/FP05020401.jsp", related: loanLinks },
  guaranteeFee: { category: "주거·부동산", title: "전세보증금 반환보증 보증료 지원: 최대 40만원 확인", summary: "전세보증금 반환보증에 가입하면서 낸 보증료를 지자체가 환급하는 국토교통부 지원사업입니다.", status: "지자체별 예산 확인 필요", checkedAt: "2026-09-02", audience: ["HUG·HF·SGI 반환보증에 가입한 임차인", "보증료 지원 대상인지 확인하려는 사람"], benefits: ["2025년 3월 31일 이후 보증 가입자는 지원 상한이 최대 40만 원으로 안내됩니다.", "청년·신혼부부는 기납부 보증료, 그 외 대상자는 보증료의 90% 범위에서 지원됩니다."], checks: ["주소지 지자체의 예산과 접수창구를 확인하세요.", "청년 연령은 지자체 조례에 따라 다를 수 있습니다.", "신혼부부는 혼인신고일 7년 이내 여부를 확인하세요."], sourceName: "HUG 국토부 보증료 지원사업", sourceUrl: "https://www.khug.or.kr/jeonse/web/s05/s050601.jsp", related: loanLinks },
  youthRent: { category: "청년·가족", title: "청년 월세 지원: 신청 가능 여부 확인하는 방법", summary: "청년 월세 지원은 중앙정부와 지방자치단체 사업의 모집기간·대상·지원액이 서로 다릅니다.", status: "최신 모집공고 확인 필요", checkedAt: "2026-09-02", audience: ["부모와 별도로 거주하며 월세를 내는 청년", "현재 접수 중인 월세지원을 찾는 사람"], benefits: ["중앙정부와 지자체가 청년 주거비 경감 사업을 운영합니다.", "지자체별 별도 사업이 수시 공고될 수 있습니다."], checks: ["복지로와 거주지 공고를 함께 확인하세요.", "소득·재산, 임대차계약과 월세 납부자료를 준비하세요.", "과거 공고의 신청기간을 현재 모집기간으로 오해하지 마세요."], sourceName: "복지로 복지서비스 찾기", sourceUrl: "https://www.bokjiro.go.kr/ssis-tbu/index.do", related: loanLinks },
  didimdol: { category: "대출·금융", title: "내집마련 디딤돌대출: 주택 구입 전 확인 순서", summary: "디딤돌대출은 무주택 실수요자의 주택 구입자금을 지원하는 정책대출입니다. 계약 전에 세대원 무주택, 소득·자산, 대상주택과 신청시기를 함께 확인해야 합니다.", status: "공식 상품 운영 확인", checkedAt: "2026-09-02", audience: ["첫 집 구입을 준비하는 무주택 세대", "일반 주택담보대출과 정책대출을 비교하는 사람"], benefits: ["주택도시기금 기준에 따라 주택 구입자금을 심사합니다.", "생애최초·신혼가구 등 해당 유형에 따라 조건이 달라질 수 있습니다."], checks: ["세대주와 세대원 무주택 요건을 확인하세요.", "소득·순자산과 주택가격·면적 기준은 접수일 공고를 확인하세요.", "매매계약과 소유권이전 시점에 따른 신청기한을 놓치지 마세요."], sourceName: "주택도시기금 내집마련 디딤돌대출", sourceUrl: "https://nhuf.molit.go.kr/FP/FP05/FP0503/FP05030101.jsp", related: [{ label: "대출 이자 계산기", href: "/calculators/loan-interest" }, { label: "주택 취득세 계산기", href: "/calculators/home-acquisition-tax" }] },
  bogeumjari: { category: "대출·금융", title: "보금자리론 조건: 고정금리 주택담보대출 확인사항", summary: "보금자리론은 한국주택금융공사가 공급하는 장기 고정금리 주택담보대출입니다. 주택가격과 소득, 주택보유 수, LTV·DTI 및 상환방식을 함께 비교해야 합니다.", status: "공식 상품 운영 확인", checkedAt: "2026-09-02", audience: ["고정금리 주택담보대출을 찾는 사람", "주택 구입·기존 대출 상환 조건을 비교하는 사람"], benefits: ["대출 실행일부터 만기까지 고정금리가 적용되는 정책모기지입니다.", "일반형 외에도 신청 방식과 가구 특성에 따른 우대조건이 있습니다."], checks: ["담보주택 가격과 부부합산 소득 요건을 확인하세요.", "LTV·DTI와 실제 한도는 개인별 심사 결과가 다를 수 있습니다.", "대출 후 추가주택 처분의무와 중도상환수수료를 확인하세요."], sourceName: "한국주택금융공사 보금자리론", sourceUrl: "https://www.hf.go.kr/ko/sub01/sub01_01_01.do", related: loanLinks },
  earnedIncomeCredit: { category: "근로·소득", title: "근로장려금 신청자격: 가구·소득·재산 확인 순서", summary: "근로장려금은 일하지만 소득이 적은 가구의 근로를 장려하고 소득을 지원하는 제도입니다. 가구유형, 부부합산 소득과 가구원 재산을 기준연도에 맞춰 확인해야 합니다.", status: "2026년 공식 안내 확인", checkedAt: "2026-09-02", audience: ["근로·사업·종교인 소득이 있는 저소득 가구", "정기신청과 반기신청 중 무엇이 해당하는지 찾는 근로자"], benefits: ["가구유형과 총소득 등에 따라 산정된 장려금을 지급합니다.", "근로소득만 있는 경우 정기 또는 반기신청 가능 여부를 확인할 수 있습니다."], checks: ["단독·홑벌이·맞벌이 가구 구분을 먼저 확인하세요.", "기준연도의 부부합산 총소득과 가구원 전체 재산을 확인하세요.", "반기신청은 근로소득만 있는 경우 등 별도 조건이 있습니다."], sourceName: "국세청 근로장려금 안내", sourceUrl: "https://www.nts.go.kr/nts/cm/cntnts/cntntsView.do?cntntsId=7784&mi=2450", related: salaryLinks },
  learningCard: { category: "근로·소득", title: "국민내일배움카드 신청과 지원내용 확인", summary: "국민내일배움카드는 직업능력개발훈련이 필요한 국민에게 훈련비를 지원하는 제도입니다. 카드 발급과 실제 훈련과정 수강신청은 구분해 진행해야 합니다.", status: "상시신청 공식 확인", checkedAt: "2026-09-02", audience: ["취업·이직을 위해 직업훈련을 찾는 사람", "재직 중 새로운 직무 역량을 배우려는 사람"], benefits: ["고용24 안내 기준 기본 훈련비와 대상별 추가 지원이 제공됩니다.", "고용센터 방문 또는 고용24에서 카드 발급을 신청할 수 있습니다."], checks: ["지원 제외 대상과 카드 발급 심사 여부를 확인하세요.", "과정별 자비부담액과 출석·수료 조건을 확인하세요.", "카드 발급 후 원하는 훈련과정을 별도로 신청해야 합니다."], sourceName: "고용24 국민내일배움카드 발급안내", sourceUrl: "https://www.work24.go.kr/hr/h/a/1100/selectIssuGudn.do", related: salaryLinks }
} satisfies Record<string, PolicyData>;
