import Link from "next/link";
import { AdSlot } from "@/components/ads/AdSlot";
import { Phase2Calculator, type Phase2CalculatorKind } from "@/components/calculators/Phase2Calculator";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { Container } from "@/components/layout/Container";
import { Accordion } from "@/components/ui/Accordion";
import { absoluteUrl } from "@/lib/utils/seo";
import type { SourceReference } from "@/lib/constants/sourceReferences";

export interface Phase2PageData { kind: Phase2CalculatorKind; path: string; title: string; description: string; category: string; categoryHref: string; guideHref: string; guideTitle: string; reference: SourceReference; useful: string[]; steps: string[]; example: string; cautions: string[]; faqs: { question: string; answer: string }[]; related: { href: string; label: string }[] }

export function Phase2CalculatorPage({ data }: { data: Phase2PageData }) {
  const breadcrumbs = [{ label: "홈", href: "/" }, { label: data.category, href: data.categoryHref }, { label: data.title }];
  const jsonLd = [{ "@context": "https://schema.org", "@type": "WebApplication", name: data.title, url: absoluteUrl(data.path), applicationCategory: "FinanceApplication", operatingSystem: "Web", offers: { "@type": "Offer", price: "0", priceCurrency: "KRW" } }, { "@context": "https://schema.org", "@type": "BreadcrumbList", itemListElement: breadcrumbs.map((item, index) => ({ "@type": "ListItem", position: index + 1, name: item.label, item: absoluteUrl(item.href ?? data.path) })) }, { "@context": "https://schema.org", "@type": "FAQPage", mainEntity: data.faqs.map((faq) => ({ "@type": "Question", name: faq.question, acceptedAnswer: { "@type": "Answer", text: faq.answer } })) }];
  return <Container className="py-10 sm:py-14">{jsonLd.map((value, index) => <script key={index} type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(value) }} />)}<Breadcrumbs items={breadcrumbs} /><h1 className="mt-4 text-2xl font-bold text-ink sm:text-3xl">{data.title}</h1><p className="mt-2 max-w-3xl text-sm leading-relaxed text-ink-soft sm:text-base">{data.description}</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-1 text-xs text-ink-muted"><span>적용 기준일 {data.reference.effectiveDate}</span><span>최종 검토일 {data.reference.lastReviewedAt}</span><a href={data.reference.sourceUrl} target="_blank" rel="noreferrer" className="font-medium text-brand hover:underline">{data.reference.sourceName} 확인 →</a></div><div className="mt-8"><Phase2Calculator kind={data.kind} /></div><div className="mt-8"><AdSlot id={`${data.kind}-bottom`} /></div><div className="mt-14 space-y-12"><Section title="이런 경우에 유용해요"><List items={data.useful} /></Section><Section title="사용 방법"><ol className="mt-3 list-decimal space-y-1.5 pl-5 text-sm leading-relaxed text-ink-soft">{data.steps.map((item) => <li key={item}>{item}</li>)}</ol></Section><Section title="계산 기준"><p className="mt-3 text-sm leading-relaxed text-ink-soft">{data.reference.scope}. {data.reference.notes}</p><p className="mt-2 text-sm leading-relaxed text-ink-soft">제외 조건: {data.reference.excludedConditions.join(", ")}.</p></Section><Section title="가상 예시"><p className="mt-3 text-sm leading-relaxed text-ink-soft">{data.example}</p></Section><Section title="주의사항"><List items={data.cautions} /></Section><Section title="자주 묻는 질문"><div className="mt-3"><Accordion items={data.faqs} /></div></Section><section className="rounded-card border border-hairline bg-white p-6"><h2 className="text-lg font-bold text-ink">함께 확인해 보세요</h2><div className="mt-3 flex flex-wrap gap-x-5 gap-y-2"><Link href={data.guideHref} className="text-sm font-semibold text-brand hover:underline">{data.guideTitle} →</Link>{data.related.map((item) => <Link key={item.href} href={item.href} className="text-sm font-semibold text-brand hover:underline">{item.label} →</Link>)}</div></section></div></Container>;
}
function Section({ title, children }: { title: string; children: React.ReactNode }) { return <section><h2 className="text-xl font-bold text-ink">{title}</h2>{children}</section>; }
function List({ items }: { items: string[] }) { return <ul className="mt-3 list-disc space-y-1.5 pl-5 text-sm leading-relaxed text-ink-soft">{items.map((item) => <li key={item}>{item}</li>)}</ul>; }

