import Link from "next/link";
import { CalculatorCTA } from "@/components/guides/CalculatorCTA";
import { Breadcrumbs } from "@/components/layout/Breadcrumbs";
import { Container } from "@/components/layout/Container";

export interface PracticalGuideData { title: string; intro: string; reviewedAt: string; facts: string[]; sections: { title: string; paragraphs: string[]; list?: string[] }[]; sources: { name: string; url: string }[]; links: { label: string; href: string }[] }

export function PracticalGuide({ data }: { data: PracticalGuideData }) {
  return <Container className="max-w-3xl py-10 sm:py-14"><Breadcrumbs items={[{ label: "홈", href: "/" }, { label: "급여·노동", href: "/salary-work" }, { label: data.title }]} /><article><h1 className="mt-4 text-2xl font-bold text-ink sm:text-3xl">{data.title}</h1><p className="mt-4 text-base leading-8 text-ink-soft">{data.intro}</p><p className="mt-3 text-xs text-ink-muted">최종 내용 검토: {data.reviewedAt}</p><section className="mt-8 rounded-card border border-hairline bg-surface-subtle p-6"><h2 className="text-lg font-bold text-ink">먼저 확인할 핵심 기준</h2><ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-ink-soft">{data.facts.map((fact) => <li key={fact}>{fact}</li>)}</ul></section><div className="mt-10 space-y-10">{data.sections.map((section, index) => <div key={section.title}><section><h2 className="text-xl font-bold text-ink">{section.title}</h2>{section.paragraphs.map((paragraph) => <p key={paragraph} className="mt-3 text-sm leading-7 text-ink-soft">{paragraph}</p>)}{section.list && <ul className="mt-3 list-disc space-y-2 pl-5 text-sm leading-7 text-ink-soft">{section.list.map((item) => <li key={item}>{item}</li>)}</ul>}</section>{index === Math.min(1, data.sections.length - 1) && <CalculatorCTA hrefs={data.links.map(link => link.href)} />}</div>)}</div><section className="mt-10 rounded-card border border-brand/20 bg-brand-light p-6"><h2 className="text-lg font-bold text-ink">관련 도구와 자료</h2><div className="mt-3 flex flex-wrap gap-x-5 gap-y-3">{data.links.map((link) => <Link key={link.href} href={link.href} className="font-semibold text-brand hover:underline">{link.label} →</Link>)}</div></section><section className="mt-10 border-t border-hairline pt-6"><h2 className="text-lg font-bold text-ink">공식 출처</h2><ul className="mt-3 space-y-2 text-sm">{data.sources.map((source) => <li key={source.url}><a href={source.url} target="_blank" rel="noreferrer" className="font-medium text-brand hover:underline">{source.name} ↗</a></li>)}</ul><p className="mt-3 text-xs leading-6 text-ink-muted">개별 사실관계에 따라 적용 결과가 달라질 수 있습니다. 실제 분쟁이나 신고 전에는 고용노동부 1350 또는 관할 지방고용노동관서에 확인하세요.</p></section></article></Container>;
}
